package com.smbc.messageBoxes
{
	public final class MenuBoxItems
	{
		public static const GAME_PAD_INFO:String = "game pad info",
		PLAY_NEW_VERSION:String = "play new version",
		OKAY:String = "okay",
		CANCEL:String = "cancel",
		YES:String = "yes",
		NO:String = "no",
		VALUE_SEP:String = ":  ",
		ON:String = "on",
		OFF:String = "off",
		
		LOAD:String = "load",
		SAVE:String = "save",
		
		// main menu
		LOAD_GAME:String = "load game",
		NEW_GAME:String = "new game",
		QUICK_PLAY:String = "quick play",
		RESUME_GAME:String = "resume game",
		OPTIONS:String = "options",
		QUIT_GAME:String = "quit game",
		LOAD_SAVE_GAME:String = "load / save",
		VIEW_STATS:String = "view stats",
		LINKS:String = "links",
		
		// options
		SET_BUTTONS:String = "Buttons",
		DISABLE_CHARACTERS:String = "disable characters",
		TUTORIALS:String = "tutorials",
		CHEAT_NOTIFY:String = "cheat notify",
		GRAPHICS_OPTIONS:String = "Skins",
		GENERAL_OPTIONS:String = "General",
		LOCK_FRAME_RATE:String = "Lock Frame Rate",
		SOUND_OPTIONS:String = "Sound",
		CHEATS:String = "Cheats",
		
		// sounds
		MUSIC:String = "music",
		SFX:String = "sfx",
		MUSIC_TYPE:String = "music console",
		MUSIC_QUALITY:String = "music quality",
		MUSIC_SET:String = "music set",
		
		// graphics
		LIMIT_SKINS:String = "Active Skins",
		DISABLE_SKINS:String = "hide/show skins",
		CHANGE_MAP_SKIN:String = "change map skin",
		RANDOM_MAP_SKIN:String = "Random Map Skin",
		ENEMY_SKIN:String = "enemy skin",
		INTERFACE_SKIN:String = "interface skin",
		GAME_BOY_FILTER:String = "Game Boy Filter",
		CLASSIC_SPECIAL_INPUT:String = "Classic Special",
		VIEW_WIKI:String = "Wiki",
		FACEBOOK:String = "Facebook",
		TWITTER:String = "Twitter",
		YOUTUBE:String = "Youtube",
		GOOGLE_PLUS:String = "Google Plus",
		SUPER_RETRO_SQUAD:String = "SRS Info",
		CHARACTER_PALETTE:String = "Character Palette",
		MAP_PALETTE:String = "Map Palette",
		ENEMY_PALETTE:String = "Enemy Palette",
		INTERFACE_PALETTE:String = "Interface Palette",
		PALETTE_TARGET:String = "Palette Target",
		CHANGE_CHAR_SKIN:String = "Change Character Skin",
		BACK_TO_MAIN_MENU:String = "back to main menu",
		FULL_SCREEN_MODE:String = "full screen mode",
		BACK:String = "back",
		ENTER_CODE:String = "Enter Code",
		
		// disable skins
		DISABLE_CHARACTER_SKINS:String = "character skins",
		DISABLE_MAP_SKINS:String = "map skins",
		ENABLE_ALL_SKINS:String = "enable all skins",
		BIT_8_ONLY:String = "8-bit only",
		BIT_16_ONLY:String = "16-bit only",
		GB_ONLY:String = "gameboy only",
		SHARP_X1_ONLY:String = "sharp x1 only",
		ATARI_ONLY:String = "atari only",
		CLASSIC:String = "classic",
		CLASSIC_16_BIT:String = "classic 16-bit",
		
		// new game menu
		GAME_DIFFICULTY:String = "Game Difficulty",
		MAP_DIFFICULTY:String = "Map Difficulty",
		MAP_PACK:String = "Map Set",
		GAME_MODE:String = "Game Mode",
		POWERUP_MODE:String = "Powerup Mode",
		CUSTOMIZE_WEAPONS:String = "customize weapons",
		START_GAME:String = "Start Game",
		// console type
		CURRENT:String = "current",
		/*NES:String = "nes",
		SUPER_NES:String = "super nes",
		GAMEBOY:String = "game boy",
		NINTENDO:String = "nintendo",*/
		NES:String = "nes",
		SUPER_NES:String = "super nintendo",
		GAMEBOY:String = "gameBoy",
		NINTENDO:String = "nintendo",
		MIX_IT_UP:String = "mix it up",
		
		// classic settings
		BILL_FIRST_WEAPON:String = "Bill First",
		BILL_SECOND_WEAPON:String = "Bill Second",
		LINK_WEAPON:String = "Link",
//		BILL_FLOWER_WEAPON:String = "Bill Flower Weapon",
//		LANCE_MUSHROOM_WEAPON:String = "Bill Mushroom Weapon",
//		LANCE_FLOWER_WEAPON:String = "Bill Flower Weapon",
		RYU_START_WEAPON:String = "Ryu Start",
		RYU_EXTRA_WEAPON:String = "Ryu Extra",
		SAMUS_WEAPON:String = "Samus",
		SIMON_START_WEAPON:String = "Simon Start",
		SIMON_EXTRA_WEAPON:String = "Simon Extra",
		SOPHIA_WEAPON:String = "Sophia",
		MEGA_MAN_WEAPON:String = "Mega Man",
		BASS_WEAPON:String = "Bass",
			
		// difficulty settings
		MORE_DIFFICULTY_SETTINGS:String = "More Settings",
		ATTACK_STRENGTH:String = "Attack Strength",
		LIVES_START:String = "Lives",
		ENEMY_SPEED:String = "Enemy Speed",
		REPLACE_GOOMBAS:String = "Replace Goombas",
		DAMAGE_RESPONSE:String = "When Hit",
		ITEM_DROP_RATE:String = "Item Drop Rate",
		PIRANHAS:String = "Piranhas",
		START_WITH_MUSHROOM:String = "Start with Mushroom",
		RESTORE_DEFAULTS:String = "Restore Defaults",
			
		// difficulties
		VERY_EASY:String = "very easy",
		EASY:String = "easy",
		NORMAL:String = "normal",
		HARD:String = "hard",
		VERY_HARD:String = "very hard",
		// campaign modes
		SURVIVAL:String = "survival",
		ALL_CHARACTERS:String = "all characters",
		SINGLE_CHARACTER:String = "single character",
		SINGLE_CHARACTER_RANDOM:String = "single random",
		// skins
		SMB_NES:String = "SMB NES",
		SMB_SNES:String = "SMB SNES",
		SMB2_NES:String = "SMB2 NES",
		SMB2_SNES:String = "SMB2 SNES",
		SMB3_NES:String = "SMB3 NES",
		SMB3_SNES:String = "SMB3 SNES",
		SUPER_MARIO_WORLD:String = "SMW",
		SUPER_MARIO_LAND_2:String = "SML2",
		SMB_LL:String = "SMB: Lost Levels",
		SMB_ANN:String = "SMB: ANN",
		SMB_SPECIAL:String = "SMB Special",
		ATARI:String = "Atari",
		BLASTER_MASTER:String = "Blaster Master",
		CASTLEVANIA:String = "Castlevania",
		ZELDA_II:String = "Zelda II",
		DEMON_RETURNS:String = "Demon Returns",
		INVISIBLE:String = "Invisible",
		NEW_SUPER_MARIO_BROS:String = "New Super Mario Bros.",
		
		// mappacks
		MAP_PACK_SMB:String = "SMB",
		MAP_PACK_SMB_SPECIAL:String = "Special",
		
		// cheats
		INFINITE_TIME:String = "infinite time",
		EXTRA_CHECKPOINTS:String = "extra checkpoints",
		EVERYONE_CAN_STOMP:String = "Everyone can stomp",
		ALL_GROUND_IS_BRICKS:String = "All ground is bricks",
		ALL_PIRANHAS_RED:String = "all piranhas red",
		ALL_HAMMER_BROS:String = "all hammer bros",
		ALL_WEAPONS_PIERCE:String = "all weapons pierce",
		ALWAYS_BREAK_BRICKS:String = "always break bricks",
		CLASSIC_SIMON:String = "classic simon",
		CLASSIC_SAMUS:String = "classic samus",
		CLASSIC_SCREEN_SCROLL:String = "classic screen scroll",
		EVIL_HAMMER_BROS:String = "evil hammer bros",
		BOUNCY_PITS:String = "bouncy pits",
		WATER_MODE:String = "water mode",
		INVINCIBLE:String = "invincible",
		INFINITE_AMMO:String = "infinite ammo",
		INFINITE_LIVES:String = "infinite lives",
		INFINITE_HOVER:String = "infinite hover",
		PIRANHAS_IN_ALL_PIPES:String = "piranhas in all pipes",
		COIN_SOUND_TYPE:String = "Coin Sound",
		MEGA_MAN_HIGH_JUMP:String = "mega man high jump",
		HIDDEN_CHEAT:String = "? ? ? ? ? ?",
		STATE:String = "state",
		LEVEL_SELECT:String = "level select",
		
		// level select
		WORLD_NUMBER:String = "world number",
		LEVEL_NUMBER:String = "level number",
		GO_TO_WORLD:String = "go to world",
		BACK_TO_CHEATS_MENU:String = "back to cheats menu";
	}
}